### ISSUE TITLE
What is with the link to YourKit Java Profiler on the main page?

### ISSUE THREAD

**Issue by lodici** [magarena/magarena.github.io#8]
The looks like a commercial product which a) I don't use (does anyone else?), b) goes against the open source credo and c) seems a bit incongruous. As it is on the main landing page seems to me they are getting free advertising. For consistency, if this company is on here, then why not the other (more relevant) links in the readme.txt?

Of course, if they want to sponsor the development of Magarena ... something could be arranged! :wink:

**Comment by melvinzhang** [comment]
They did sponsor us. At one point I was debugging some performance problems in the AIs, and the existing profilers were not good enough. I noticed many open source projects mentioned YourKit so I approached them and they kindly offered us a free license key to use their commercial product in return for a mention on the project website.

That said, I haven't used it in a while so it would be fine to drop the mention as we are not longer actively using the tool. Java 7u40 and beyond comes with Flight Recorder which I've heard is also a very competent profiler.

**Comment by lodici** [comment]
> That said, I haven't used it in a while so it would be fine to drop the mention as we are no longer actively using the tool. Java 7u40 and beyond comes with Flight Recorder which I've heard is also a very competent profiler.

Ok I will get rid. Flight Recorder looks similar to [Visual VM](https://visualvm.java.net/) which can be found in the ``bin`` folder of the JDK.
